# Generated by Django 2.2.7 on 2019-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
